spring.application.name=portofolio

# loggin 레벨 설정
logging.level.com.portfolio.lhm=debug
logging.level.org.springframework.security=debug
 
# mvc jsp viewResolver 설정
spring.mvc.view.prefix=/WEB-INF/jsp/
spring.mvc.view.suffix=.jsp
 
# MariaDB 접속 설정
spring.datasource.url=jdbc:mariadb://localhost:3306/portfolio_sts_mariaDB
spring.datasource.username=portfolioMariaDB
spring.datasource.password=1234

# 드라이버 클래스명 (선택적, Spring Boot가 자동 감지하지만 명시해도 무방)
spring.datasource.driver-class-name=org.mariadb.jdbc.Driver
 
# mybatis 설정
mybatis.type-aliases-package=com.portfolio.lhm.vo
mybatis.mapper-locations=classpath:mybatis/mapper/*_SQL.xml
mybatis.configuration.map-underscore-to-camel-case=true
mybatis.configuration.jdbc-type-for-null=varchar
